# Generated by Django 5.1.1 on 2024-10-13 08:15

import ars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ars.models.assignment_upload_path),
        ),
    ]
