# Generated by Django 5.1.1 on 2024-10-13 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0002_assignment_due_date_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='assignments_reviewing', to=settings.AUTH_USER_MODEL),
        ),
    ]
