# Generated by Django 5.1.1 on 2024-10-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0004_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
